class Two(object):
    """
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
    """

    def __init__(self, less_than_number):
        self.less_than_number = less_than_number

    def solve(self):
        fib_0 = 0
        fib_1 = 1
        even_fibs = []
        while fib_1 < self.less_than_number:
            fib_0 += fib_1
            fib_1 += fib_0
            if fib_0 % 2 == 0:
                even_fibs.append(fib_0)
            if fib_1 % 2 == 0:
                even_fibs.append(fib_1)
        return sum(even_fibs)


euler_two = Two(4000000).solve()
print(euler_two)
